title: Querying Abstract Syntax Tree
#author: prataprc
description: > # this means to ignore newlines until "baseurl:"
timezone: Asia/Colombo
baseurl: "/astquery.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
social_sites:
  #github:  prataprc
  #linkedin: prataprc
  #dribbble: jekyll
  #facebook: jekyll
  #flickr: jekyll
  #instagram: jekyll
  #pinterest: jekyll
  #youtube: jekyll
  #googleplus: +jekyll

rss:

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
plugins:
  - jekyll-seo-tag
